services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    profiles:
      - keycloak
      - all
    environment:
      KEYCLOAK_ADMIN: administrator
      KEYCLOAK_ADMIN_PASSWORD: administrator
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    command: [ "start-dev", "--import-realm" ]
    ports:
      - "${KEYCLOAK_PORT}:8080"
    volumes:
      - ./container/keycloak/realms:/opt/keycloak/data/import
  platine-db:
    profiles:
      - all
      - platine-db
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${PLATINE_DB_USER}
      - POSTGRES_PASSWORD=${PLATINE_DB_PASSWORD}
      - POSTGRES_DB=${PLATINE_DB}
    command: ["postgres"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PLATINE_DB_USER} -d ${PLATINE_DB} -h localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - ${PLATINE_DB_PORT}:5432