package fr.insee.survey.datacollectionmanagement.metadata.enums;

import lombok.Getter;

@Getter
public enum PeriodEnum {

    A00(PeriodicityEnum.A, PeriodNameEnum.ANNUAL.getValue()),
    X00(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X00"),
    X01(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X01"),
    X02(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X02"),
    X03(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X03"),
    X04(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X04"),
    X05(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X05"),
    X06(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X06"),
    X07(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X07"),
    X08(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X08"),
    X09(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X09"),
    X10(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X10"),
    X11(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X11"),
    X12(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X12"),
    X13(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X13"),
    X14(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X14"),
    X15(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X15"),
    X16(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X16"),
    X17(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X17"),
    X18(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X18"),
    X19(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X19"),
    X20(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X20"),
    X21(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X21"),
    X22(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X22"),
    X23(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X23"),
    X24(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X24"),
    X25(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X25"),
    X26(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X26"),
    X27(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X27"),
    X28(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X28"),
    X29(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X29"),
    X30(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X30"),
    X31(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X31"),
    X32(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X32"),
    X33(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X33"),
    X34(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X34"),
    X35(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X35"),
    X36(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X36"),
    X37(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X37"),
    X38(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X38"),
    X39(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X39"),
    X40(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X40"),
    X41(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X41"),
    X42(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X42"),
    X43(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X43"),
    X44(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X44"),
    X45(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X45"),
    X46(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X46"),
    X47(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X47"),
    X48(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X48"),
    X49(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X49"),
    X50(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X50"),
    X51(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X51"),
    X52(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X52"),
    X53(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X53"),
    X54(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X54"),
    X55(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X55"),
    X56(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X56"),
    X57(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X57"),
    X58(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X58"),
    X59(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X59"),
    X60(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X60"),
    X61(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X61"),
    X62(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X62"),
    X63(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X63"),
    X64(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X64"),
    X65(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X65"),
    X66(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X66"),
    X67(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X67"),
    X68(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X68"),
    X69(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X69"),
    X70(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X70"),
    X71(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X71"),
    X72(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X72"),
    X73(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X73"),
    X74(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X74"),
    X75(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X75"),
    X76(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X76"),
    X77(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X77"),
    X78(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X78"),
    X79(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X79"),
    X80(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X80"),
    X81(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X81"),
    X82(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X82"),
    X83(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X83"),
    X84(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X84"),
    X85(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X85"),
    X86(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X86"),
    X87(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X87"),
    X88(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X88"),
    X89(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X89"),
    X90(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X90"),
    X91(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X91"),
    X92(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X92"),
    X93(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X93"),
    X94(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X94"),
    X95(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X95"),
    X96(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X96"),
    X97(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X97"),
    X98(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X98"),
    X99(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue() + " X99"),
    S01(PeriodicityEnum.S, PeriodNameEnum.FIRST_SEMESTER.getValue()),
    S02(PeriodicityEnum.S, PeriodNameEnum.SECOND_SEMESTER.getValue()),
    T01(PeriodicityEnum.T, PeriodNameEnum.FIRST_TRIMESTER.getValue()),
    T02(PeriodicityEnum.T, PeriodNameEnum.SECOND_TRIMESTER.getValue()),
    T03(PeriodicityEnum.T, PeriodNameEnum.THIRD_TRIMESTER.getValue()),
    T04(PeriodicityEnum.T, PeriodNameEnum.FOURTH_TRIMESTER.getValue()),
    M01(PeriodicityEnum.M, PeriodNameEnum.JANUARY.getValue()),
    M02(PeriodicityEnum.M, PeriodNameEnum.FEBRUARY.getValue()),
    M03(PeriodicityEnum.M, PeriodNameEnum.MARCH.getValue()),
    M04(PeriodicityEnum.M, PeriodNameEnum.APRIL.getValue()),
    M05(PeriodicityEnum.M, PeriodNameEnum.MAY.getValue()),
    M06(PeriodicityEnum.M, PeriodNameEnum.JUNE.getValue()),
    M07(PeriodicityEnum.M, PeriodNameEnum.JULY.getValue()),
    M08(PeriodicityEnum.M, PeriodNameEnum.AUGUST.getValue()),
    M09(PeriodicityEnum.M, PeriodNameEnum.SEPTEMBER.getValue()),
    M10(PeriodicityEnum.M, PeriodNameEnum.OCTOBER.getValue()),
    M11(PeriodicityEnum.M, PeriodNameEnum.NOVEMBER.getValue()),
    M12(PeriodicityEnum.M, PeriodNameEnum.DECEMBER.getValue()),
    B01(PeriodicityEnum.B, PeriodNameEnum.FIRST_BIMESTER.getValue()),
    B02(PeriodicityEnum.B, PeriodNameEnum.SECOND_BIMESTER.getValue()),
    B03(PeriodicityEnum.B, PeriodNameEnum.THIRD_BIMESTER.getValue()),
    B04(PeriodicityEnum.B, PeriodNameEnum.FOURTH_BIMESTER.getValue()),
    B05(PeriodicityEnum.B, PeriodNameEnum.FIFTH_BIMESTER.getValue()),
    B06(PeriodicityEnum.B, PeriodNameEnum.SIXTH_BIMESTER.getValue()),

    ;

    PeriodEnum(PeriodicityEnum period, String value) {
        this.value = value;
        this.period = period;
    }

    final PeriodicityEnum period;

    final String value;



}
