package fr.insee.survey.datacollectionmanagement.metadata.enums;

import lombok.Getter;

@Getter
public enum PeriodEnum {

    A00(PeriodicityEnum.A, PeriodNameEnum.ANNUAL.getValue()),
    X00(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X01(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X02(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X03(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X04(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X05(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X06(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X07(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X08(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X09(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X10(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X11(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X12(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X13(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X14(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X15(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X16(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X17(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X18(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X19(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X20(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X21(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X22(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X23(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X24(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X25(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X26(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X27(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X28(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X29(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X30(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X31(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X32(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X33(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X34(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X35(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X36(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X37(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X38(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X39(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X40(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X41(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X42(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X43(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X44(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X45(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X46(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X47(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X48(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X49(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X50(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X51(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X52(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X53(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X54(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X55(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X56(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X57(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X58(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X59(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X60(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X61(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X62(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X63(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X64(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X65(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X66(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X67(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X68(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X69(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X70(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X71(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X72(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X73(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X74(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X75(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X76(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X77(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X78(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X79(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X80(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X81(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X82(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X83(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X84(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X85(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X86(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X87(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X88(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X89(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X90(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X91(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X92(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X93(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X94(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X95(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X96(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X97(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X98(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    X99(PeriodicityEnum.X, PeriodNameEnum.PLURIANNUAL.getValue()),
    S01(PeriodicityEnum.S, PeriodNameEnum.FIRST_SEMESTER.getValue()),
    S02(PeriodicityEnum.S, PeriodNameEnum.SECOND_SEMESTER.getValue()),
    T01(PeriodicityEnum.T, PeriodNameEnum.FIRST_TRIMESTER.getValue()),
    T02(PeriodicityEnum.T, PeriodNameEnum.SECOND_TRIMESTER.getValue()),
    T03(PeriodicityEnum.T, PeriodNameEnum.THIRD_TRIMESTER.getValue()),
    T04(PeriodicityEnum.T, PeriodNameEnum.FOURTH_TRIMESTER.getValue()),
    M01(PeriodicityEnum.M, PeriodNameEnum.JANUARY.getValue()),
    M02(PeriodicityEnum.M, PeriodNameEnum.FEBRUARY.getValue()),
    M03(PeriodicityEnum.M, PeriodNameEnum.MARCH.getValue()),
    M04(PeriodicityEnum.M, PeriodNameEnum.APRIL.getValue()),
    M05(PeriodicityEnum.M, PeriodNameEnum.MAY.getValue()),
    M06(PeriodicityEnum.M, PeriodNameEnum.JUNE.getValue()),
    M07(PeriodicityEnum.M, PeriodNameEnum.JULY.getValue()),
    M08(PeriodicityEnum.M, PeriodNameEnum.AUGUST.getValue()),
    M09(PeriodicityEnum.M, PeriodNameEnum.SEPTEMBER.getValue()),
    M10(PeriodicityEnum.M, PeriodNameEnum.OCTOBER.getValue()),
    M11(PeriodicityEnum.M, PeriodNameEnum.NOVEMBER.getValue()),
    M12(PeriodicityEnum.M, PeriodNameEnum.DECEMBER.getValue()),
    B01(PeriodicityEnum.B, PeriodNameEnum.FIRST_BIMESTER.getValue()),
    B02(PeriodicityEnum.B, PeriodNameEnum.SECOND_BIMESTER.getValue()),
    B03(PeriodicityEnum.B, PeriodNameEnum.THIRD_BIMESTER.getValue()),
    B04(PeriodicityEnum.B, PeriodNameEnum.FOURTH_BIMESTER.getValue()),
    B05(PeriodicityEnum.B, PeriodNameEnum.FIFTH_BIMESTER.getValue()),
    B06(PeriodicityEnum.B, PeriodNameEnum.SIXTH_BIMESTER.getValue()),

    ;

    PeriodEnum(PeriodicityEnum period, String value) {
        this.value = value;
        this.period = period;
    }

    final PeriodicityEnum period;

    final String value;



}
